#!/usr/bin/env python3

import configargparse

import di
from commands import bootstrap, install, load_certificates

parser = configargparse.ArgumentParser(prog='builder2')
subparsers = parser.add_subparsers(dest='command', required=True)

if __name__ == "__main__":
    bootstrap.register(subparsers)
    install.register(subparsers)
    install.register(subparsers)
    load_certificates.register(subparsers)
    args = parser.parse_args()

    di.Container.config.from_dict(args.__dict__)

    container = di.Container()
    container.wire(modules=[__name__, install.__name__, bootstrap.__name__, load_certificates.__name__])

    args.func(args)
